apiVersion: v1
kind: Service

metadata:
  name: myservices

spec:
  selector:
    name: eurekaservices
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8000
    nodePort: 32400

  - name: https
    protocol: TCP
    port: 8761
    targetPort: 8761


