apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: alpine:latest
      command: ["sleep", "9999"]
      env:
      - name: MONGO_INITDB_DATABASE
        valueFrom:
          configMapKeyRef:
            name: mongodb
            key: database-name
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
            name: mongodb
            key: database-user
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongodb
            key: database-password
  restartPolicy: Never
