---
- name: "Templates changes verification"
  hosts: webservers
  user: fsgbu_ormb
  become: true
  
  tasks:
    - name: "Cpoying template from source location to all host"
      template:
         src: templates/index.html
         dest: /var/www/html/index.html
    

...
