--- 
- name: "This playbook is use for checking handler behaviour"
  hosts: appservers
  user: fsgbu_ormb
  become: true
  
  vars:
  - name: Suyog
    age: 18
  
  tasks:
  - name: This section to trigger event based execution
    copy:
      src: templates/index.html
      dest: /root/index.html
      mode: 0755
    notify:
    - restart service

  handlers:
  - name: restart service
    debug:
      msg: Service has been restarted

   
# Learn to print the variable
...
  
  
