--- 
- hosts: appservers
  user: fsgbu_ormb
  
  vars:
  - name: Suyog
    age: 18
    subject:
      - English
      - Hindi
      - Marathi
      - Math
  
  tasks:
  - name: This is to print debug message
    debug:
      msg: How are you {{ item }}S
    with_items: 
      - Suyog
      - Sachin
      - Suraj
      - Amit 
...
  
  
