--- 
- hosts: appservers
  user: fsgbu_ormb
  
  vars:
  - name: Suyog
    age: 18
  
  tasks:
  - name: This is to print debug message
    debug:
      msg: How are you {{ name }} 

# Learn to print the variable
...
  
  
